import os from 'os'
import path from 'path'
import { FileService } from './file.service'
import { MemoryService } from './memory.service'
import type { ConfigService } from './config.service'

export class ContextEnrichmentService {
  private static instance: ContextEnrichmentService

  private constructor() {}

  static getInstance(): ContextEnrichmentService {
    if (!ContextEnrichmentService.instance) {
      ContextEnrichmentService.instance = new ContextEnrichmentService()
    }
    return ContextEnrichmentService.instance
  }

  /**
   * 收集系统上下文信息
   */
  async getContextInfo(
    options: {
      workspaceRoot?: string | null
      configService?: ConfigService
      includeProjectLayout?: boolean
      includeOpenFiles?: boolean
      maxProjectDepth?: number
    } = {}
  ): Promise<string> {
    const {
      workspaceRoot,
      configService,
      includeProjectLayout = true,
      includeOpenFiles = true,
      maxProjectDepth = 2
    } = options

    const contextParts: string[] = []

    // 1. 系统信息
    const systemInfo = this.getSystemInfo(workspaceRoot, configService)
    contextParts.push(systemInfo)

    // 2. 规则和 Memories（合并在 rules 标签内）
    const rulesAndMemories = await this.getRulesAndMemories()
    if (rulesAndMemories) {
      contextParts.push(rulesAndMemories)
    }

    // 3. 项目文件结构
    if (includeProjectLayout && workspaceRoot) {
      const projectLayout = await this.getProjectLayout(workspaceRoot, maxProjectDepth)
      if (projectLayout) {
        contextParts.push(projectLayout)
      }
    }

    // 4. 打开的文件列表
    if (includeOpenFiles && configService) {
      const openFiles = await this.getOpenFiles(configService, workspaceRoot)
      if (openFiles) {
        contextParts.push(openFiles)
      }
    }

    return contextParts.join('\n\n')
  }

  /**
   * 获取系统信息
   */
  private getSystemInfo(workspaceRoot?: string | null, configService?: ConfigService): string {
    const platform = os.platform()
    const osVersion = os.release()
    const shell =
      configService?.getConfig?.()?.terminalSettings?.shell?.trim() ||
      (platform === 'win32' ? 'cmd' : 'sh')
    const currentDate = new Date().toLocaleString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })

    let systemInfo = `<user_info>
OS Version: ${platform} ${osVersion}
Current Date: ${currentDate}
Shell: ${shell}`

    if (workspaceRoot) {
      systemInfo += `
Workspace Path: ${workspaceRoot}
Note: Prefer using absolute paths over relative paths as tool call args when possible.`
    }

    systemInfo += '\n</user_info>'

    return systemInfo
  }

  /**
   * 获取规则和 Memories(完整的 rules 部分)
   */
  private async getRulesAndMemories(): Promise<string | null> {
    try {
      const defaultRule = '- Always respond in 中文'

      let rulesContent = `<rules>
The rules section has a number of possible rules/memories/context that you should consider. In each subsection, we provide instructions about what information the subsection contains and how you should consider/follow the contents of the subsection.



<agent_rules description="These are rules that the agent should follow if appropriate.">
${defaultRule}
</agent_rules>`

      // 获取 memories
      const memoryService = MemoryService.getInstance()
      const allMemories = await memoryService.getAllMemories()

      if (allMemories && allMemories.length > 0) {
        // 只取最近的 10 条 memories
        const recentMemories = allMemories.slice(0, 10)

        const memoriesText = recentMemories
          .map((memory) => `- ${memory.content} (ID: ${memory.id})`)
          .join('\n')

        rulesContent += `
<memories description="The following memories were generated by the agent based on the user's interactions with the agent.
        If relevant to the user query, you should follow them as you generate code, answer questions, and search the codebase.
        If you notice that any memory is incorrect, you should update it using the update_memory tool.
        ">
${memoriesText}
</memories>`
      }

      rulesContent += '\n\n</rules>'

      return rulesContent
    } catch (error) {
      console.error('Failed to get rules and memories:', error)
      return null
    }
  }

  /**
   * 获取项目文件结构(简化版)
   */
  private async getProjectLayout(
    workspaceRoot: string,
    maxDepth: number = 2
  ): Promise<string | null> {
    try {
      const projectName = path.basename(workspaceRoot)
      const structure = await this.buildProjectTree(workspaceRoot, '', maxDepth, 0)

      return `<project_layout>
Below is a snapshot of the current workspace's file structure at the start of the conversation. This snapshot will NOT update during the conversation.

${projectName}/
${structure}
</project_layout>`
    } catch (error) {
      console.error('Failed to get project layout:', error)
      return null
    }
  }

  /**
   * 递归构建项目文件树
   */
  private async buildProjectTree(
    dirPath: string,
    prefix: string,
    maxDepth: number,
    currentDepth: number
  ): Promise<string> {
    if (currentDepth >= maxDepth) {
      return ''
    }

    try {
      const items = await FileService.listDirectory(dirPath)

      // 过滤掉常见的忽略目录
      const filteredItems = items.filter((item) => {
        const name = path.basename(item.path)
        return ![
          'node_modules',
          '.git',
          'dist',
          'build',
          'out',
          '.next',
          'coverage',
          '.DS_Store'
        ].includes(name)
      })

      // 分类：目录和文件
      const directories = filteredItems.filter((item) => item.type === 'directory')
      const files = filteredItems.filter((item) => item.type === 'file')

      let result = ''

      // 先列出目录(只显示前10个)
      const limitedDirs = directories.slice(0, 10)
      for (const dir of limitedDirs) {
        const dirName = path.basename(dir.path)
        result += `${prefix}  - ${dirName}/\n`

        // 递归子目录
        if (currentDepth + 1 < maxDepth) {
          const subTree = await this.buildProjectTree(
            dir.path,
            prefix + '    ',
            maxDepth,
            currentDepth + 1
          )
          result += subTree
        }
      }

      if (directories.length > 10) {
        result += `${prefix}  ... (${directories.length - 10} more directories)\n`
      }

      // 再列出文件(只显示前20个)
      const limitedFiles = files.slice(0, 20)
      for (const file of limitedFiles) {
        const fileName = path.basename(file.path)
        result += `${prefix}  - ${fileName}\n`
      }

      if (files.length > 20) {
        result += `${prefix}  ... (${files.length - 20} more files)\n`
      }

      return result
    } catch (error) {
      console.error(`Failed to build tree for ${dirPath}:`, error)
      return ''
    }
  }

  /**
   * 获取当前打开的文件列表
   */
  private async getOpenFiles(
    configService: ConfigService,
    workspaceRoot?: string | null
  ): Promise<string | null> {
    try {
      const uiState = configService.getUIState()
      const openFiles = uiState.codeEditor?.openFiles || []

      if (openFiles.length === 0) {
        return null
      }

      // 只显示当前项目的文件
      const relevantFiles = workspaceRoot
        ? openFiles.filter((f: { path: string }) => f.path.startsWith(workspaceRoot))
        : openFiles

      if (relevantFiles.length === 0) {
        return null
      }

      const filesList = relevantFiles
        .map((f: { path: string }) => {
          const relativePath = workspaceRoot ? path.relative(workspaceRoot, f.path) : f.path
          return `  - ${relativePath}`
        })
        .join('\n')

      const activeFile = uiState.codeEditor?.activeFilePath
      const activeFileName =
        activeFile && workspaceRoot
          ? path.relative(workspaceRoot, activeFile)
          : activeFile
            ? path.basename(activeFile)
            : 'none'

      return `<open_and_recently_viewed_files>
Recently viewed files (recent at the top, oldest at the bottom):
${filesList}

Files that are currently open and visible in the user's IDE:
  - ${activeFileName} (currently focused file)

Note: these files may or may not be relevant to the current conversation. Use the read_file tool if you need to get the contents of some of them.
</open_and_recently_viewed_files>`
    } catch (error) {
      console.error('Failed to get open files:', error)
      return null
    }
  }
}
