/** AI 行内补全（FIM）可调参数 */
export const COMPLETION = {
  TIMEOUT_MS: 5000,
  PREFIX_CONTEXT_LINES: 30,
  SUFFIX_CONTEXT_LINES: 10,
  TEMPERATURE: 0.2,
  MAX_RETRY_ATTEMPTS: 2,
  MAX_COMPLETION_LINES: 20
} as const
